<?php

/**
 * @file
 * @package   Tawk.to module for Backdrop CMS
 * @copyright (C) TBC
 * @license   GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */

require_once 'views/widget.php.inc';
require_once 'views/admin.php.inc';

/**
 * Retrieves widget details from config file.
 */
function tawkto_get_widget()
{
    return array(
            'page_id' => config_get('tawkto.settings','page_id'),
            'widget_id' => config_get('tawkto.settings','widget_id'),
        );
}

/**
 * Hook for adding widget script to every page.
 */
function tawkto_page_build(&$page)
{
    global $base_url;
    
    // backend checking; do not show chat widget on admin page(s)
    if (path_is_admin(current_path())) {
        return;
    }
    
    $widget = tawkto_get_widget();

    if ($widget['page_id'] === '' || $widget['widget_id'] === '') {
        return null;
    }
    $page_id = $widget['page_id'];
    $widget_id = $widget['widget_id'];

    // get visibility options
    $options = config_get('tawkto.settings','widget_options');
    if ($options) {
        $options = json_decode($options);

        // prepare visibility
        $currentUrl = $base_url.$_SERVER["REQUEST_URI"];
        if (false==$options->always_display) {

            $showPages = json_decode($options->show_oncustom);
            $show = false;
            foreach ($showPages as $slug) {
                // if (stripos($currentUrl, $slug)!==false) {
                if ($currentUrl == $slug) {
                    $show = true;
                    break;
                }
            }
            
            // taxonomy page
            if (arg(0) ==  "taxonomy" && arg(1) == "term" && is_numeric(arg(2)) && arg(3) == "") {
                if (false != $options->show_oncategory) {
                    $show = true;
                }
            }
            
            if (backdrop_is_front_page()) {
                if (false != $options->show_onfrontpage) {
                    $show = true;
                }                
            }

            if (!$show) {
                return;
            }
        } else {
            if (isset($options->hide_oncustom)) {
                $hide_pages = json_decode($options->hide_oncustom);
                $show = true;
                
                // $currentUrl = urlencode($current_page);
                $currentUrl = (string) $currentUrl;
                foreach ($hide_pages as $slug) {
                    $slug = (string) htmlspecialchars($slug); // we need to add htmlspecialchars due to slashes added when saving to database
                    
                    // if (stripos($currentUrl, $slug)!==false) {
                    if ($currentUrl == $slug) {
                        $show = false;
                        break;
                    }
                }
                
                if (!$show) {
                    return;
                }
            }
        }
    }

    $page['page_bottom']['tawkto_widget'] = array(
            '#markup' => tawkto_render_widget($page_id, $widget_id),
        );

    return $page;
}

/**
 * Hooks up configuration menu items and paths for ajax call endpoints.
 */
function tawkto_menu()
{

  $items = array();
  $items['admin/config/tawk'] = array(
        'title'            => 'tawk.to',
        'description'      => 'tawk.to configuration',
        'position'         => 'left',
        'weight'           => -100,
        'page callback'    => 'system_admin_menu_block_page',
        'access arguments' => array('administer site configuration'),
        'file'             => 'system.admin.inc',
        'file path'        => backdrop_get_path('module', 'system'),
      );

  $items['admin/config/tawk/widget'] = array(
        'title'            => 'Widget',
        'description'      => 'Included tawk.to widget configuration',
        'page callback'    => 'tawkto_widget_customization',
        'access arguments' => array('administer site configuration'),
        'type'             => MENU_NORMAL_ITEM,
      );

  $items['admin/config/tawk/setwidget'] = array(
        'title'            => 'Set widget',
        'page callback'    => 'tawkto_set_widget',
        'access arguments' => array('administer site configuration'),
        'type'             => MENU_CALLBACK,
      );

  $items['admin/config/tawk/removewidget'] = array(
        'title'            => 'Remove widget',
        'page callback'    => 'tawkto_remove_widget',
        'access arguments' => array('administer site configuration'),
        'type'             => MENU_CALLBACK,
      );

  $items['admin/config/tawk/setoptions'] = array(
        'title'            => 'Set widget options',
        'page callback'    => 'tawkto_widget_options',
        'access arguments' => array('administer site configuration'),
        'type'             => MENU_CALLBACK,
      );

  return $items;
}

/**
 * Displays widget configuration iframe.
 *
 * Configuration iframe contains functionality from
 * tawk.to server which is responsible for verifying
 * user login details and also retrieves his page
 * and widget list and comunicates back to upper
 * page so that changes can be saved in DB.
 */
function tawkto_widget_customization()
{
    $base_url = tawkto_get_base_url();
    $iframe_url = tawkto_get_iframe_url();
    $widget = tawkto_get_widget();

    global $user;
    $sameUser = true;
    $value = config_get('tawkto.settings', 'widget_user_id');
    if (!empty($value) && $user->uid!=$value) {
        $sameUser = false;
    }
    
    $displayOpts = config_get('tawkto.settings','widget_options');
    if ($displayOpts && !empty($displayOpts)) {
        $displayOpts = json_decode($displayOpts);
    } else {
        $displayOpts = null;
    }

    return tawkto_render_widget_iframe($base_url, $iframe_url, $widget, $displayOpts, $sameUser);
}

/**
 * Constructs url for configuration iframe.
 */
function tawkto_get_iframe_url()
{
    $widget = tawkto_get_widget();
    if (!$widget) {
        $widget = array(
                'page_id'   => '',
                'widget_id' => '',
            );
    }
    return tawkto_get_base_url() . '/generic/widgets?currentWidgetId=' . $widget['widget_id'] . '&currentPageId=' . $widget['page_id'];
}

/**
 * Base url for tawk.to application which serves iframe.
 */
function tawkto_get_base_url()
{
    return 'https://plugins.tawk.to';
}

/**
 * Ajax endpoint which is used to set selected widget details.
 */
function tawkto_set_widget()
{

    if (!isset($_POST['pageId']) || !isset($_POST['widgetId'])) {
        return backdrop_json_output(array('success' => false));
    }

    if (preg_match('/^[0-9A-Fa-f]{24}$/', $_POST['pageId']) !== 1 || preg_match('/^[a-z0-9]{1,50}$/i', $_POST['widgetId']) !== 1) {
        return backdrop_json_output(array('success' => false));
    }

    config_set('tawkto.settings', 'page_id', $_POST['pageId']);
    config_set('tawkto.settings', 'widget_id', $_POST['widgetId']);

    global $user;
    if ($user->uid) {
        config_set('tawkto.settings', 'widget_user_id', $user->uid);
    }

    backdrop_json_output(array('success' => true));
}

/**
 * Ajax endpoint which is used to remove currently selected widget details.
 */
function tawkto_remove_widget($a = 0, $b = 0)
{
	$config = config('tawkto.settings');
	$config->clear('page_id');
	$config->clear('widget_id');
	$config->save;

    backdrop_json_output(array('success' => true));
}

function tawkto_widget_options()
{
    $jsonOpts = array(
            'always_display' => false,
            'hide_oncustom' => array(),
            'show_onfrontpage' => false,
            'show_oncategory' => false,
            'show_onproduct' => false,
            'show_oncustom' => array(),
        );

    if (isset($_REQUEST['options']) && !empty($_REQUEST['options'])) {
        $options = explode('&', $_REQUEST['options']);
        foreach ($options as $post) {
            list($column, $value) = explode('=', $post);
            switch ($column) {
                case 'hide_oncustom':
                case 'show_oncustom':
                    // replace newlines and returns with comma, and convert to array for saving
                    $value = urldecode($value);
                    $value = str_ireplace(["\r\n", "\r", "\n"], ',', $value);
                    $value = explode(",", $value);
                    $value = (empty($value)||!$value)?array():$value;
                    $jsonOpts[$column] = json_encode($value);
                    break;
                
                case 'show_onfrontpage':
                case 'show_oncategory':
                case 'show_onproduct':
                case 'always_display':
                // default:
                    $jsonOpts[$column] = ($value==1)?true:false;
                    break;
            }
        }
    }
    config_set('tawkto.settings', 'widget_options', json_encode($jsonOpts));

    backdrop_json_output(array('success' => true));
}
